name: DAST - OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    name: Build and Run Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run application
        run: |
          nohup mvn spring-boot:run &
          sleep 10 # pequena pausa inicial

      - name: Wait for port 8080
        run: |
          for i in {1..30}; do
            nc -z localhost 8080 && echo "App is up!" && break
            echo "Waiting for app on port 8080..."
            sleep 3
          done
          nc -z localhost 8080 || (echo "App did not start on port 8080" && exit 1)

  zap-scan:
    name: ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: build-and-run
    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8080'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório de Vulnerabilidades DAST da FinSecure'
          fail_action: true
